gantt/ej2-javascript-gantt-toc.html
=> documentation(EJ2-71942): Fixed toc issues

ej2-javascript/gantt/columns/check-box-columns.md, ej2-javascript/gantt/selection/selection.md
=> Documentation(833199): Fixed Broken link issue

ej2-javascript/code-snippet/gantt/exporting-blob-data-cs1/blobdata.js, ej2-javascript/code-snippet/gantt/exporting-blob-data-cs1/index.js, ej2-javascript/code-snippet/gantt/newrowposition-cs1/index.js, ej2-javascript/code-snippet/gantt/newrowposition-cs1/systemjs.config.js, ej2-javascript/code-snippet/gantt/virtual-scroll-cs3/index.ts, ej2-javascript/code-snippet/gantt/virtual-scroll-cs3/systemjs.config.js, ej2-javascript/gantt/managing-tasks/task-bar-editing.md
change the broken sample in ts
missing some imports in ug documentation
- Common guidelines / Core team guideline
- Specification document
- Requirement document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
Guidelines/documents are not followed.
No
Import the missing imports
NA
- Did you run the automation against your fix? NO
- Is there any API name change? NO
- Is there any existing behavior change of other features due to this code change? NO
- Does your new code introduce new warnings or binding errors? NO
- Does your code pass all FxCop and StyleCop rules? NA
- Did you record this case in the unit test or UI test? NO
=> bug(EJ2-834806):brokensample

ej2-javascript/gantt/index.md, ej2-javascript/gantt/selection/selection.md, ej2-javascript/gantt/state-persistence.md
Resolved broken link issue for Gantt component
=> bug(839526): Resolved broken link issue for Gantt component

ej2-javascript/code-snippet/gantt/virtual-scroll-cs3/index.ts
Changed path for the datasource
=> bug(EJ2-841667): Preview is not working in the virtualization UG

ej2-javascript/code-snippet/gantt/event-markers-cs2/datasource.ts, ej2-javascript/code-snippet/gantt/event-markers-cs2/es5-datasource.js, ej2-javascript/code-snippet/gantt/event-markers-cs2/index.css, ej2-javascript/code-snippet/gantt/event-markers-cs2/index.js, ej2-javascript/code-snippet/gantt/event-markers-cs2/index.ts, ej2-javascript/code-snippet/gantt/event-markers-cs2/js/index.html, ej2-javascript/code-snippet/gantt/event-markers-cs2/systemjs.config.js, ej2-javascript/code-snippet/gantt/event-markers-cs2/ts/index.html, ej2-javascript/gantt/event-markers.md
sample added to display event Markers in stacked manner
=> documentation(385415): sample added to display event Markers in stacked manner

ej2-javascript/code-snippet/gantt/label-position-cs1/datasource.ts, ej2-javascript/code-snippet/gantt/label-position-cs1/es5-datasource.js, ej2-javascript/code-snippet/gantt/label-position-cs1/index.css, ej2-javascript/code-snippet/gantt/label-position-cs1/index.js, ej2-javascript/code-snippet/gantt/label-position-cs1/index.ts, ej2-javascript/code-snippet/gantt/label-position-cs1/js/index.html, ej2-javascript/code-snippet/gantt/label-position-cs1/systemjs.config.js, ej2-javascript/code-snippet/gantt/label-position-cs1/ts/index.html, ej2-javascript/gantt/event-markers.md
Need to add UG for label positions in js/ts documentation has been updated.
=> documentation(EJ2-379338):Need to add UG for label positions in js documentation has been updated

ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/datasource.ts, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/es5-datasource.js, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/index.css, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/index.js, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/index.ts, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/js/index.html, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/systemjs.config.js, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/ts/index.html, ej2-javascript/gantt/event-markers.md
Need to explain how to prevent overlapping of event markers in ts documentation has been updated.
=> documentation(EJ2-378146):explain how to prevent overlapping of event markers in ts documentation has been updated

ej2-javascript/code-snippet/gantt/predecessor-cs6/datasource.ts, ej2-javascript/code-snippet/gantt/predecessor-cs6/es5-datasource.js, ej2-javascript/code-snippet/gantt/predecessor-cs6/index.css, ej2-javascript/code-snippet/gantt/predecessor-cs6/index.js, ej2-javascript/code-snippet/gantt/predecessor-cs6/index.ts, ej2-javascript/code-snippet/gantt/predecessor-cs6/js/index.html, ej2-javascript/code-snippet/gantt/predecessor-cs6/systemjs.config.js, ej2-javascript/code-snippet/gantt/predecessor-cs6/ts/index.html, ej2-javascript/gantt/task-dependency.md
Dependency show/hide sample added and updated
=> documentation(835699-): sample added

ej2-javascript/gantt/js/es5-getting-started.md, ej2-javascript/gantt/ts/getting-started.md
Need to resolve the Page With Redirect - EJ2 docs links for gantt documentation
Resolved the Page With Redirect - EJ2 docs links for gantt documentation by adding the correct links
NA
No area is affected due to this changes.
NA
NA
* Did you run the automation against your implementation? NA
* Is there any API name change? No
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? Yes
* Did you record this case in the unit test or UI test? NA
=> documentation(839873): Add the correct path.

ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/index.js, ej2-javascript/code-snippet/gantt/eventmarkeroverlap-cs1/index.ts
DayMarkers has been injected for eventmarker overlap file.
=> documentation(EJ2-378146): daymarkers for event marker overlap file has been injected

ej2-javascript/code-snippet/gantt/getting-started-cs24/datasource.ts, ej2-javascript/code-snippet/gantt/getting-started-cs24/es5-datasource.js, ej2-javascript/code-snippet/gantt/getting-started-cs24/index.css, ej2-javascript/code-snippet/gantt/getting-started-cs24/index.js, ej2-javascript/code-snippet/gantt/getting-started-cs24/index.ts, ej2-javascript/code-snippet/gantt/getting-started-cs24/js/index.html, ej2-javascript/code-snippet/gantt/getting-started-cs24/systemjs.config.js, ej2-javascript/code-snippet/gantt/getting-started-cs24/ts/index.html, ej2-javascript/code-snippet/gantt/getting-started-cs25/datasource.ts, ej2-javascript/code-snippet/gantt/getting-started-cs25/es5-datasource.js, ej2-javascript/code-snippet/gantt/getting-started-cs25/index.css, ej2-javascript/code-snippet/gantt/getting-started-cs25/index.js, ej2-javascript/code-snippet/gantt/getting-started-cs25/index.ts, ej2-javascript/code-snippet/gantt/getting-started-cs25/js/index.html, ej2-javascript/code-snippet/gantt/getting-started-cs25/systemjs.config.js, ej2-javascript/code-snippet/gantt/getting-started-cs25/ts/index.html, ej2-javascript/code-snippet/gantt/getting-started-cs26/datasource.ts, ej2-javascript/code-snippet/gantt/getting-started-cs26/es5-datasource.js, ej2-javascript/code-snippet/gantt/getting-started-cs26/index.css, ej2-javascript/code-snippet/gantt/getting-started-cs26/index.js, ej2-javascript/code-snippet/gantt/getting-started-cs26/index.ts, ej2-javascript/code-snippet/gantt/getting-started-cs26/js/index.html, ej2-javascript/code-snippet/gantt/getting-started-cs26/systemjs.config.js, ej2-javascript/code-snippet/gantt/getting-started-cs26/ts/index.html, ej2-javascript/gantt/ej2-javascript-gantt-toc.html, ej2-javascript/gantt/ej2-typescript-gantt-toc.html, ej2-javascript/gantt/managing-tasks/validation.md
=> Added validation rule doc

ej2-javascript/code-snippet/gantt/getting-started-cs24/systemjs.config.js, ej2-javascript/code-snippet/gantt/getting-started-cs25/systemjs.config.js, ej2-javascript/code-snippet/gantt/getting-started-cs26/systemjs.config.js
Validation Rule adding Condition for system congif
=> Validation Rule adding Condition for system congif

ej2-javascript/gantt/ej2-javascript-gantt-toc.html, ej2-javascript/gantt/ej2-typescript-gantt-toc.html
documentation for pdf exporting content.
=> documentation(EJ2-861370): committed pdf export

ej2-javascript/gantt/accessibility.md
Made improvements in Accessibility vue gantt
=> documentation(864980): Update changes in the accessibility

ej2-javascript/code-snippet/gantt/global-cs2/index.js, ej2-javascript/code-snippet/gantt/global-cs2/index.ts, ej2-javascript/code-snippet/gantt/pdf-export-column-template-cs1/js/index.html, ej2-javascript/code-snippet/gantt/pdf-export-column-template-cs1/ts/index.html, ej2-javascript/code-snippet/gantt/predecessor-cs6/js/index.html, ej2-javascript/code-snippet/gantt/predecessor-cs6/systemjs.config.js, ej2-javascript/code-snippet/gantt/predecessor-cs6/ts/index.html
TS documentation preview sample not opening issues has been resolved.
=> documentation(864645): TS documentation preview sample not opening issue

ej2-javascript/code-snippet/gantt/capturerecords-cs1/ts/index.html, ej2-javascript/code-snippet/gantt/getting-started-cs5/ts/index.html, ej2-javascript/code-snippet/gantt/global-cs2/ca-gregorian.js, ej2-javascript/code-snippet/gantt/global-cs2/index.js, ej2-javascript/code-snippet/gantt/global-cs2/index.ts, ej2-javascript/code-snippet/gantt/global-cs2/js/index.html, ej2-javascript/code-snippet/gantt/global-cs2/numbers.js, ej2-javascript/code-snippet/gantt/predecessor-cs6/ts/index.html, ej2-javascript/gantt/managing-tasks/editing-tasks.md
React documentation preview sample console errors has been resolved.
=> 865778: JS documentation preview sample console errors

ej2-javascript/code-snippet/gantt/getting-started-cs5/ts/index.html, ej2-javascript/code-snippet/gantt/global-cs2/ca-gregorian.js, ej2-javascript/code-snippet/gantt/global-cs2/index.js, ej2-javascript/code-snippet/gantt/global-cs2/index.ts, ej2-javascript/code-snippet/gantt/global-cs2/js/index.html, ej2-javascript/code-snippet/gantt/global-cs2/numbers.js, ej2-javascript/code-snippet/gantt/predecessor-cs6/ts/index.html
JS documentation preview sample console errors has been resolved.
=> 865778: JS hotfix documentation preview sample console errors

ej2-javascript/code-snippet/gantt/getting-started-cs5/js/index.html, ej2-javascript/code-snippet/gantt/getting-started-cs5/ts/index.html, ej2-javascript/code-snippet/gantt/global-cs2/index.js, ej2-javascript/code-snippet/gantt/global-cs2/js/index.html, ej2-javascript/code-snippet/gantt/predecessor-cs6/ts/index.html
JS/TS documentation preview sample not opening issues has been resolved.
=> documentatio(864645): TS documentation preview sample not opening issue

ej2-javascript/gantt/accessibility.md
Need to modified the icons on accessibility document. The Icons are newly created for the compilance measuring.
[866555](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/866555)
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is …
=> 866555: Need to modified the icons on accessibility document

ej2-javascript/gantt/pdf-export/pdf-export.md, ej2-javascript/gantt/timeline/timeline.md
hi @Gowri-V-L,
Please review the changes made.
Regards,
Scholar.
=> SEO-178962-JavaScript-page-Improvement

ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/datasource.ts, ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/es5-datasource.js, ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/index.css, ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/index.js, ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/index.ts, ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/js/index.html, ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/systemjs.config.js, ej2-javascript/code-snippet/gantt/projectview-multitaskbar-cs1/ts/index.html, ej2-javascript/gantt/taskbar.md
Adding document for multi taskbar support in project view.
NA
Added documentation for multi taskbar support in project view..
Tag label `update-guideline-coreteam` or `update-guideline-productteam`. 
NA
Provide details about the areas or combinations that have been tested against this code changes.
If yes, provide the breaking commit details / MR here. 
NA
Feature matrix document updated
Automation details - Mark `Is Automated` field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the bug is automated. 
If the same issue is reproduced in ej2, what will you do?
* [ x  NA
Is this common issue need to be addressed in the same component or on other components in our platform? 
NA
Confirm whether this feature is ensured in both Blazor Server and WASM
Is there any new API or …
=> 876168: Project view multi taskbar js

ej2-javascript/code-snippet/gantt/rows-cs14/datasource.ts, ej2-javascript/code-snippet/gantt/rows-cs14/es5-datasource.js, ej2-javascript/code-snippet/gantt/rows-cs14/index.css, ej2-javascript/code-snippet/gantt/rows-cs14/index.js, ej2-javascript/code-snippet/gantt/rows-cs14/index.ts, ej2-javascript/code-snippet/gantt/rows-cs14/js/index.html, ej2-javascript/code-snippet/gantt/rows-cs14/systemjs.config.js, ej2-javascript/code-snippet/gantt/rows-cs14/ts/index.html, ej2-javascript/code-snippet/gantt/rows-cs15/datasource.ts, ej2-javascript/code-snippet/gantt/rows-cs15/es5-datasource.js, ej2-javascript/code-snippet/gantt/rows-cs15/index.css, ej2-javascript/code-snippet/gantt/rows-cs15/index.js, ej2-javascript/code-snippet/gantt/rows-cs15/index.ts, ej2-javascript/code-snippet/gantt/rows-cs15/js/index.html, ej2-javascript/code-snippet/gantt/rows-cs15/systemjs.config.js, ej2-javascript/code-snippet/gantt/rows-cs15/ts/index.html, ej2-javascript/code-snippet/gantt/rows-cs16/datasource.ts, ej2-javascript/code-snippet/gantt/rows-cs16/es5-datasource.js, ej2-javascript/code-snippet/gantt/rows-cs16/index.css, ej2-javascript/code-snippet/gantt/rows-cs16/index.js, ej2-javascript/code-snippet/gantt/rows-cs16/index.ts, ej2-javascript/code-snippet/gantt/rows-cs16/js/index.html, ej2-javascript/code-snippet/gantt/rows-cs16/systemjs.config.js, ej2-javascript/code-snippet/gantt/rows-cs16/ts/index.html, ej2-javascript/gantt/managing-tasks/managing-tasks.md
Add topic  custom dialog modal  for all platfrom
Add topic  custom dialog modal  for all platfrom
- Common guidelines / Core team guideline
- Specification document
- Requirement document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
Guidelines/documents are not followed.
No
NA
- Did you run the automation against your fix? YES
- Is there any API name change? NO
- Is there any existing behavior change of other features due to this code change? NO
- Does your new code introduce new warnings or binding errors? NO
- Does your code pass all FxCop and StyleCop rules? NA
- Did you record this case in the unit test or UI test? YES
=> documentation(870318):dialog

ej2-javascript/code-snippet/gantt/pdf-export-header-template-cs1/index.js, ej2-javascript/code-snippet/gantt/pdf-export-header-template-cs1/index.ts, ej2-javascript/code-snippet/gantt/pdf-export-taskbar-template-cs1/datasource.ts, ej2-javascript/code-snippet/gantt/pdf-export-taskbar-template-cs1/es5-datasource.js, ej2-javascript/code-snippet/gantt/pdf-export-taskbar-template-cs1/index.js, ej2-javascript/code-snippet/gantt/pdf-export-taskbar-template-cs1/index.ts, ej2-javascript/code-snippet/gantt/pdf-export-taskbar-template-cs1/js/index.html, ej2-javascript/code-snippet/gantt/pdf-export-taskbar-template-cs1/ts/index.html, ej2-javascript/code-snippet/gantt/pdf-export-tasklabel-template-cs1/index.js, ej2-javascript/code-snippet/gantt/pdf-export-tasklabel-template-cs1/index.ts
Adding document content to taskbar template, tasklabel template and header tempalte.
NA
Added documentation content to  taskbar template, tasklabel template and header tempalte.
Tag label `update-guideline-coreteam` or `update-guideline-productteam`. 
NA
Provide details about the areas or combinations that have been tested against this code changes.
If yes, provide the breaking commit details / MR here. 
NA
Feature matrix document updated
Automation details - Mark `Is Automated` field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the bug is automated. 
If the same issue is reproduced in ej2, what will you do?
* [ x  NA
Is this common issue need to be addressed in the same component or on other components in our platform? 
NA
Confirm whether this feature is ensured in …
=> 875490: Adding document content to taskbar template, tasklabel template and header tempalte.
